### ISSUE TITLE
Relancer le serveur sur carbon

### ISSUE THREAD

**Issue by JackDesBwa** [haum/timeoAPI#2]

**Comment by matael** [comment]
Carbon est hors service jusqu'a ce qu'on trouve un disque dur de remplacement.

**Comment by gagath** [comment]
C'est quel type de disque ?

Si c'est un disque spécifique serveur genre SCSI 15k tr/min ça va être compliqué à trouver ; par contre si c'est du SATA j'ai un disque 3,5" 80 Go ou un 3,5" 320 Go si besoin de plus de place.

**Comment by neomilium** [comment]
C'est un 3,5" SATA de mémoire, par contre on ne peut accéder à la salle
serveur qu'à partir du 17 août.

Le 12 août 2015 15:42, Romain Porte notifications@github.com a écrit :

> C'est quel type de disque ?
> 
> Si c'est un disque spécifique serveur genre SCSI 15k tr/min ça va être
> compliqué à trouver ; par contre si c'est du SATA j'ai un disque 3,5" 80 Go
> ou un 3,5" 320 Go si besoin de plus de place.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/haum/timeoAPI/issues/2#issuecomment-130309167.

## 

Romuald

**Comment by gagath** [comment]
Carbon est de nouveau en service, reste à relancer ce serveur donc.

**Comment by sebvallee** [comment]
Il me semble que @Matael disait l'autre jour, en séance, que ce n'était pas si simple car les infras coté Setram avaient changé...

**Comment by matael** [comment]
En effet, une partie des infras a déjà changé. Rien n'empèche toutefois d'adapter le code :)

Avec un peu de chance, les soucis étaient liés à la cohabitation des deux infras et donc peut être que si la migration est terminée on pourra relancer le scrapping.

**Comment by matael** [comment]
Je ferme cette issue, ça va faire deux ans et je ne vois pas l'intérêt d'adapter quoi que ce soit. Le but de la manoeuvre était de pousser LMM à ajouter "OpenData" dans les demandes pour la nouvelle concession: ça n'a pas été fait et ça ne le sera pas de si tôt.
